kind: pipeline
name: go-1-11

workspace:
  base: /go
  path: src/github.com/takaaki82/drone-sandbox

steps:
  - name: test
    image: golang:1.11
    commands:
      - go build -v ./go
      - go test -v ./...

---
kind: pipeline
name: go-1-12

workspace:
  base: /go
  path: src/github.com/takaaki82/drone-sandbox

steps:
  - name: test
    image: golang:1.12
    commands:
      - go test -v ./...
